server:
  port: 5003

spring:
  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/task_user_service
    username: root
    password: Son@re12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
